version: '3.8'
services:
      db:
        image: postgres
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: devonl
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: production-db
        volumes:
          - postgres-data:/var/lib/postgresql/data


      # pgadmin:
      #   image: dpage/pgadmin4
      #   ports:
      #     - "8080:80"
      #   environment:
      #     PGADMIN_DEFAULT_EMAIL: 110386@gmail.com
      #     PGADMIN_DEFAULT_PASSWORD: 1234
      #   volumes:
      #     - pgadmin-data:/var/lib/pgadmin

      server:
        build: .
        depends_on:
          - db
          # - pgadmin
        ports:
          - "3010:3000"
        environment:
          PGDATABASE: production-db
          PGUSER: devonl
          PGPASSWORD: 1234
          PGHOST: db
volumes:
      postgres-data:
        driver: local
      # pgadmin-data:
      #   driver: local

